spring:
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      location: ./
# spring.mvc.hiddenmethod.filter.enabled=true
# spring.webflux.hiddenmethod.filter.enabled=true
