spring:
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
      static-locations: [
        classpath:/META-INF/resources/,
        classpath:/resources/,
        classpath:/static/,
        classpath:/public/,
        file:./ext_resources/
      ]
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  webflux:
    hiddenmethod:
      filter:
        enabled: true
# spring.mvc.hiddenmethod.filter.enabled=true
# spring.webflux.hiddenmethod.filter.enabled=true
